[package]
name = "math"
version = "0.1.0"
edition = "2024"
description = "stateless, no-std mathematical engine for PCLMM"

[dependencies]
primitive-types = {version = "0.12.1", default-features = false}
ruint = { workspace = true } #prefer using this over primitive-types , it is vastly superior in my opinion

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ["std"]
std = ["ruint/std"]